language: node_js
node_js: 12
sudo: required
dist: trusty
before_script:
  - npm install
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
branches:
  only:
    - gh-pages
    - /.*/
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run npm run test
  - xvfb-run npm run bench
